# derived_terms/Makefile.bench				* -*- Makefile -*-

benchs: $(noinst_PROGRAMS)
	@echo '=====================';				\
	echo '|Derived Terms bench|';				\
	echo '=====================';				\
	for n_states in $$(seq 15 15); do			\
	   echo "----------------------For $$n_states states";	\
	   echo "--------------VCSN:";				\
	   ./derived_terms-bench $$n_states;			\
	done
