# Makefile.flags -*- Makefile -*-
# $Id$

AM_CXXFLAGS = -Wall -W -Wno-unused -ftemplate-depth-99
AM_CPPFLAGS = \
	-I$(top_srcdir)/include -I$(top_srcdir)/src/tests/ \
	-I$(top_builddir)/include -I$(top_builddir)/src/tests/
