# eps_removal/Makefile.bench				* -*- Makefile -*-

bench: $(noinst_PROGRAMS)
	@echo '===================';				\
	echo '|eps_removal bench|';				\
	echo '===================';				\
	for n_value in $$(seq 1 20); do				\
	   n_value=$${n_value}0					\
	   echo "----------------------For $${n_value}0:";	\
	   ./eps_removal-bench $${n_value};			\
	done
