# eps_removal/Makefile.bench				* -*- Makefile -*-

bench: all
	@mkdir aut_linear_eps;					\
	echo '===================';			\
	echo '|eps_removal bench|';			\
	echo '===================';			\
	for n in $$(seq 1 20); do			\
	   echo "----------------------For $${n}0:";	\
	   ./eps_removal_bench $${n}0;			\
	done

bench-clean:
	rm -rf aut_linear_eps
