# derived_terms/Makefile.bench				* -*- Makefile -*-

bench: all
	@mkdir default;					\
	echo '=====================';			\
	echo '|Derived Terms bench|';			\
	echo '=====================';			\
	for n in 15; do					\
	   echo "----------------------For $$n states";	\
	   echo "--------------VCSN:";			\
	   ./derived_terms_bench $$n;			\
	done

bench-clean:
	rm -rf default
