## Vaucanson test suite.
SUBDIRS = \
algebra_alphabet_set_alpha \
algebra_alphabet_set_char \
algebra_alphabet_set_int \
algebra_alphabet_set_pair_char_int \
algebra_free_monoid_product_string \
algebra_free_monoid_string \
algebra_numerical_semiring_double \
algebra_numerical_semiring_float \
algebra_numerical_semiring_int \
algebra_numerical_semiring_rational \
algebra_series_krat_bool_string \
algebra_series_krat_cderivation \
algebra_series_krat_derivation \
algebra_series_krat_double_string \
algebra_series_krat_int_string \
algebra_series_krat_partial_derivation \
algebra_series_polynom_bool_string \
algebra_series_polynom_double_string \
algebra_series_polynom_int_string \
algebra_tropical_semiring_max_bool \
algebra_tropical_semiring_max_double \
algebra_tropical_semiring_max_float \
algebra_tropical_semiring_max_int \
algebra_tropical_semiring_max_rational \
algebra_tropical_semiring_min_bool \
algebra_tropical_semiring_min_double \
algebra_tropical_semiring_min_float \
algebra_tropical_semiring_min_int \
algebra_tropical_semiring_min_rational \
boolean_automaton \
boolean_transducer \
char_char_boolean_automaton \
context_headers_boolean \
context_headers_boolean_transducer \
context_headers_fmp_transducer \
context_headers_int_boolean \
context_headers_r \
context_headers_z \
context_headers_z_fmp_transducer \
context_headers_z_max_plus \
context_headers_z_min_plus \
context_headers_z_transducer \
fmp_transducer \
int_boolean_automaton \
int_int_boolean_automaton \
r_automaton \
z_automaton \
z_fmp_transducer \
z_max_plus_automaton \
z_min_plus_automaton \
z_transducer \
  .
