# minimization_2n/Makefile.bench				* -*- Makefile -*-

bench: $(noinst_PROGRAMS)
	@echo '================';					\
	echo '|Quotient bench|';					\
	echo '================';					\
	for n_states in $$(seq 5 13); do				\
	    echo "----------------------For power $$n_states";		\
	    echo "--------------VCSN (over Z):";			\
	    ./quotient_z-bench $$n_states;				\
	    echo "--------------VCSN (over B):";			\
	    ./quotient_bool-bench $$n_states;				\
	done;
