# minimization_2n/Makefile.bench				* -*- Makefile -*-

bench: all
	@mkdir bool;					\
	mkdir z;					\
	echo '================';			\
	echo '|Quotient bench|';			\
	echo '================';			\
	for n in 5 6 7 8 9 10 11 12 13; do		\
	    echo "----------------------For power $$n";	\
	    echo "--------------VCSN (over Z):";	\
	    ./quotient_z_bench $$n;			\
	    echo "--------------VCSN (over B):";	\
	    ./quotient_bool_bench $$n;			\
	done;

bench-clean:
	rm -rf bool
	rm -rf z
